"""initial

Revision ID: 64184a08e1eb
Revises: 
Create Date: 2026-03-28 22:39:35.535984
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '64184a08e1eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'BUSINESS_OWNER', 'TEAM_MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_personality', sa.String(length=50), nullable=True),
    sa.Column('ai_language_preference', sa.String(length=20), nullable=True),
    sa.Column('upsell_aggressiveness', sa.Integer(), nullable=True),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=True),
    sa.Column('business_hours_only', sa.Boolean(), nullable=True),
    sa.Column('business_hours_start', sa.String(length=5), nullable=True),
    sa.Column('business_hours_end', sa.String(length=5), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('away_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_business_owner', 'businesses', ['owner_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('platform', sa.Enum('FACEBOOK', 'WHATSAPP', name='platform'), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_business', 'analytics_events', ['business_id'], unique=False)
    op.create_index('idx_analytics_business_type_created', 'analytics_events', ['business_id', 'event_type', 'created_at'], unique=False)
    op.create_index('idx_analytics_created', 'analytics_events', ['created_at'], unique=False)
    op.create_index('idx_analytics_type', 'analytics_events', ['event_type'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('target_segment', sa.Enum('HOT_LEAD', 'WARM_LEAD', 'COLD_LEAD', 'REPEAT_BUYER', 'VIP', 'UNHAPPY', 'NEW', name='customersegment'), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('replied_count', sa.Integer(), nullable=True),
    sa.Column('is_ai_personalized', sa.Boolean(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_business', 'campaigns', ['business_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('FACEBOOK', 'WHATSAPP', name='platform'), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('segment', sa.Enum('HOT_LEAD', 'WARM_LEAD', 'COLD_LEAD', 'REPEAT_BUYER', 'VIP', 'UNHAPPY', 'NEW', name='customersegment'), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'ANGRY', name='sentimenttype'), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_business', 'customers', ['business_id'], unique=False)
    op.create_index('idx_customer_platform', 'customers', ['platform_id'], unique=False)
    op.create_index('idx_customer_segment', 'customers', ['segment'], unique=False)
    op.create_table('facebook_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('page_access_token', sa.Text(), nullable=False),
    sa.Column('page_picture_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', name='pageconnectionstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id')
    )
    op.create_index('idx_fb_business', 'facebook_pages', ['business_id'], unique=False)
    op.create_index('idx_fb_page_id', 'facebook_pages', ['page_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('PRODUCT', 'FAQ', 'CUSTOM_QA', 'POLICY', 'GENERAL', name='knowledgebasetype'), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_business', 'knowledge_bases', ['business_id'], unique=False)
    op.create_index('idx_kb_type', 'knowledge_bases', ['type'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_business', 'products', ['business_id'], unique=False)
    op.create_index('idx_product_category', 'products', ['category'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('plan', sa.Enum('STARTER', 'GROWTH', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptionplan'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIAL', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('messages_limit', sa.Integer(), nullable=True),
    sa.Column('pages_limit', sa.Integer(), nullable=True),
    sa.Column('messages_used', sa.Integer(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('facebook_page_id', sa.String(), nullable=True),
    sa.Column('platform', sa.Enum('FACEBOOK', 'WHATSAPP', name='platform'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'AI_HANDLING', 'HUMAN_HANDLING', 'CLOSED', 'FLAGGED', name='conversationstatus'), nullable=True),
    sa.Column('detected_language', sa.String(length=20), nullable=True),
    sa.Column('current_sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'ANGRY', name='sentimenttype'), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('is_abandoned', sa.Boolean(), nullable=True),
    sa.Column('abandoned_recovered', sa.Boolean(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facebook_page_id'], ['facebook_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_business', 'conversations', ['business_id'], unique=False)
    op.create_index('idx_conv_customer', 'conversations', ['customer_id'], unique=False)
    op.create_index('idx_conv_platform', 'conversations', ['platform'], unique=False)
    op.create_index('idx_conv_status', 'conversations', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('delivery_charge', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_conversation_id', sa.String(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('idx_order_business', 'orders', ['business_id'], unique=False)
    op.create_index('idx_order_customer', 'orders', ['customer_id'], unique=False)
    op.create_index('idx_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'AI', 'HUMAN_AGENT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=20), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'ANGRY', name='sentimenttype'), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('platform_message_id', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_msg_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_msg_role', 'messages', ['role'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('variant', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_index('idx_msg_role', table_name='messages')
    op.drop_index('idx_msg_created', table_name='messages')
    op.drop_index('idx_msg_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_number', table_name='orders')
    op.drop_index('idx_order_customer', table_name='orders')
    op.drop_index('idx_order_business', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_conv_status', table_name='conversations')
    op.drop_index('idx_conv_platform', table_name='conversations')
    op.drop_index('idx_conv_customer', table_name='conversations')
    op.drop_index('idx_conv_business', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('subscriptions')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_index('idx_product_business', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_kb_type', table_name='knowledge_bases')
    op.drop_index('idx_kb_business', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('idx_fb_page_id', table_name='facebook_pages')
    op.drop_index('idx_fb_business', table_name='facebook_pages')
    op.drop_table('facebook_pages')
    op.drop_index('idx_customer_segment', table_name='customers')
    op.drop_index('idx_customer_platform', table_name='customers')
    op.drop_index('idx_customer_business', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_campaign_business', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('idx_analytics_type', table_name='analytics_events')
    op.drop_index('idx_analytics_created', table_name='analytics_events')
    op.drop_index('idx_analytics_business_type_created', table_name='analytics_events')
    op.drop_index('idx_analytics_business', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('idx_business_owner', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
